= Steps

. Install https://github.com/git-for-windows/git/releases[PortableGit].
. Edit `<PortableGit>\mingw64\etc\gitconfig` and change `autocrlf` to `input` instead of `auto`.
. Create shortcut to start `mintty`.
.. _Target_ `<PortableGit>\usr\bin\mintty.exe`
.. _Start in_ `%USERPROFILE%`
. Start `mintty`.
. `cd $USERPROFILE`
. `git clone git@github.com:kohanyirobert/vagrant.git Work`
. `cd Work`
. Create `.ssh` and `.aws` directories.
.. If an SSH key is named like __id_rsa__ or __id_rsaN__ (where _N_ is a number) it'll get picked up during Vagrant provisioning (see `script.sh` for more).
. Run `script.cmd` which will link some config files into `%USERPROFILE%`, like `.minttyrc` and `.mintty`.
.. Start `mintty` with _Run as administrator_. 
. Install Vagrant's `vbguest` plugin with `vagrant plugin install vagrant-vbguest`.
. Run `vagrant up`.
.. Lubuntu is kind of whacky. After the first `vagrant up` it won't be running, so do a `vagrant reload`.
.. After this when showing the GUI in VBox the Lubuntu login screen will be shown, however the size of the screen won't change dynamically. Switch to fullscreen view, login, then logout and it'll be okay.
. Edit `<PortableGit>\mingw64\etc\gitconfig` and change back `autocrlf` to `auto` if needed.
